//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE3Launcher.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SE3Launcher.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created by LavaPower.
        /// </summary>
        public static string About_Credits {
            get {
                return ResourceManager.GetString("About_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GLSL Version : {0}.
        /// </summary>
        public static string About_GLSLVersion {
            get {
                return ResourceManager.GetString("About_GLSLVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OpenGL Version : {0}.
        /// </summary>
        public static string About_GLVersion {
            get {
                return ResourceManager.GetString("About_GLVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Renderer Name : {0}.
        /// </summary>
        public static string About_RendererName {
            get {
                return ResourceManager.GetString("About_RendererName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SE3 Launcher Version : {0}.
        /// </summary>
        public static string About_SE3LauncherVersion {
            get {
                return ResourceManager.GetString("About_SE3LauncherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SE3 Version : {0}.
        /// </summary>
        public static string About_SE3Version {
            get {
                return ResourceManager.GetString("About_SE3Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vendor Name : {0}.
        /// </summary>
        public static string About_VendorName {
            get {
                return ResourceManager.GetString("About_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launcher Parameters.
        /// </summary>
        public static string LauncherParameters {
            get {
                return ResourceManager.GetString("LauncherParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string LauncherParameters_Language {
            get {
                return ResourceManager.GetString("LauncherParameters_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string LauncherParameters_Validate {
            get {
                return ResourceManager.GetString("LauncherParameters_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Project.
        /// </summary>
        public static string ProjectsPage_CreateProject {
            get {
                return ResourceManager.GetString("ProjectsPage_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string ProjectsPage_Delete {
            get {
                return ResourceManager.GetString("ProjectsPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Launch.
        /// </summary>
        public static string ProjectsPage_Launch {
            get {
                return ResourceManager.GetString("ProjectsPage_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project Name.
        /// </summary>
        public static string ProjectsPage_NameProject {
            get {
                return ResourceManager.GetString("ProjectsPage_NameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open in Explorer.
        /// </summary>
        public static string ProjectsPage_OpenExplorer {
            get {
                return ResourceManager.GetString("ProjectsPage_OpenExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SE3 Version : {0}.
        /// </summary>
        public static string ProjectsPage_SE3Version {
            get {
                return ResourceManager.GetString("ProjectsPage_SE3Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        public static string SideMenu_Exit {
            get {
                return ResourceManager.GetString("SideMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à News.
        /// </summary>
        public static string SideMenu_News {
            get {
                return ResourceManager.GetString("SideMenu_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projects.
        /// </summary>
        public static string SideMenu_Projects {
            get {
                return ResourceManager.GetString("SideMenu_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SharpEngine 3.
        /// </summary>
        public static string SideMenu_SE3 {
            get {
                return ResourceManager.GetString("SideMenu_SE3", resourceCulture);
            }
        }
    }
}
